StareAbyss/FoodsVsMiceAutoAssistant

function/battle/CardManager.py

当CardManager检测到结束后, 会调整其状态为已中止, 并根据该状态防重复调用stop函数.

v1.3.1 修复了战斗中手动中止时, 直接闪退的问题

---

function/scattered/TodoTimerManager.py
function/script/QMW_1_load_settings.py
function/script/QMW_2_log.py
function/script/QMW_3_service.py
function/script/ThreadTodo.py
resource/ui/FAA_3.0.ui

新增TodoTimerManager类, 封装相关方法; 大幅重构service类以适用定时启动.

v1.3.1 重大更新, 完成定时启动任务事项的功能.

---

function/script/QMW_3_service.py
function/script/ThreadTodo.py

使用新的ThreadTodo线程实例实现了这一点, 并通过id参数定义不同run方法, i…d=1者基本不变, id=2者run方法仅有执行作战一项; 使用互相传递的信号与槽函数+锁, 实现了 Thread1创建任务, 激活 自身和Thread2同时进行作战, 并在完成时解锁.

v1.3.1 尝试性完成多线程单人作战功能

---

function/battle/Card.py

v1.3.1 战斗方案执行器 - 放卡时, 通过偏移对应点击位置, 以规避点到领取奖励按钮, 老方案危险区域先识图检测再点击, 已移除

---

function/common/bg_img_match.py

对图像识别功能增加新特性: 当使用的template图片为png格式, 且其中包含alpha通道为非255的像素时, 提取所有非255像素为掩模纯黑部分, 作为匹配的遮罩. 即无视模板图片中的透明部分进行匹配.

v1.3.1 图像识别功能新特性: 自动无视template的透明像素进行匹配.

---

function/core_battle/Card.py

该bug来自为处理棉花糖卡片独特的卡背图案, 导致对普通卡片冷却判定的失效; 通过更新算法修复了这一重大bug! 现在 当能量不足时, 会优先等待能量以放置高优先级卡片, 而不是直接放置低优先级的低能量需求卡片.

v1.3.1 修正了 自动战斗-自动放卡 中, 优先级队列在低火苗能量情况下失效的bug.

---

function/common/bg_img_match.py
function/common/bg_img_screenshot.py
function/core/FAA.py
function/core/FAABattle.py
function/core/FAA_ActionInterfaceJump.py
function/core/FAA_ActionQuestReceiveRewards.py
function/core/FAA_BattleARoundPreparation.py
function/core/Todo.py
function/core/analyzer_of_loot_logs.py
function/core_battle/Card.py
function/core_battle/get_position_in_battle.py
function/scattered/get_house_id.py

重大优化 当进行图像截取时, 增加了root_handle可选参数, 当该句柄对应窗口最小化时, 会强制显示它并置于最低窗口优先级, 进行防呆的同时, 尽可能不干扰用户正常使用. 对所有的截图+识图+动作的组合函数均已增加该参数, 大部分重要的识图节点应用该参数.
规范化了相关函数的命名和注释
注: 对于嵌套在主窗口内的子窗口截图时, 直接通过传参而非查找上一级中的主窗口, 意义在于节省性能资源防止大量查找句柄结构, 且增加通用库的可用性不局限在单一的句柄结构中.

v1.3.1 重大优化, 图像截取时, 若窗口最小化, 将自动提升至已激活窗口的最低一级.

---

function/core/Todo.py
function/core_battle/CardManager.py

优化了 自动战斗-状态监测/武器技能/自动拾取/使用卡片 的动作间隔的设置方式.
修改为在Todo类中的battle_check_interval属性进行设置后, 自动根据比例应用,
状态监测是x1,
武器技能和自动拾取是x10,
使用卡片是/50. 
为未来增加相关设置项提供一定基础.

v1.3.1 将自动战斗中各项动作间隔设置为动态调整的比例关系, 而非固定值.

---

function/core/FAABattle.py
function/core_battle/CardManager.py
function/globals/thread_action_queue.py
test/profile_load.py
test/test_action_queue_timer.py
test/test_queue_click.py

添加了战斗中检查点击队列的状态的函数, 以及动作队列相关的单元测试. 用以调查该版本出现的部分电脑机型上, 动作队列生产者速度>消费者速度.

v1.3.1 添加了调查部分电脑机型上, 动作队列生产者速度>消费者速度问题的测试单元.

---

function/core/FAA_BattleARoundPreparation.py
function/core/Todo.py
function/core/analyzer_of_loot_logs.py
function/scattered/loots_and_chest_data_save_and_post.py

图像识别 - 战利品识别 - 逻辑优化.
根据战利品数据是否可以被构筑为有向无环图, 判断战利品数据是否有效, 再记录至本地log和发送至服务器. FAA类中的保存战利品和宝箱物品统计和明细的函数, 已移动至单独的文件.

v1.4.0-beta.3 图像识别 - 战利品识别.  根据战利品数据是否可以被构筑为有向无环图, 判断战利品数据是否有效.

---

function/core/FAA.py
function/core/Todo.py
function/core_battle/Card.py
test/test.py

代码规范.
将 ban_card_list 和 list_ban_card 字段和变量全部统一为 ban_card_list. 
将 是否需要使用钥匙 从 is_use_key 的字段和变量全部统一为 need_key, 以与 是否已经使用钥匙的字段和变量 is_used_key 做区分.

v1.4.0-beta.4 将是否需要使用钥匙 从 is_use_key 的字段和变量全部统一为 need_key.

---

function/core/FAA.py

日氪一元.
修正部分情况下, 充值途径变少后出现功能障碍的问题.

v1.4.1-beta.1

---

function/common/bg_img_match.py
resource/ui/FAA_3.0.ui

查找图像并点击函数 -> 是否启用不一样的点击句柄 异常消失.
重新排版 软件主页的新元素.

v1.4.1-beta.1 修复多人协同中, 被异常回调的修正.

---

.gitignore

v1.4.1-beta.1 修复Gitignore, pycharm文件夹的错误名称.

---

function/core/QMW_0_load_ui_file.py
resource/ui/FAA_3.0.ui
resource/ui/draglabel.py

感觉是非常规缩放的字体问题不是代码的锅，像是选的字体天然缺陷

1.5.0 beta3 整合字体为stylesheet

---

function/core/Todo.py

v1.5.0-beta.4 去除 任务事项耗时通报 的时间小数点.

---

function/core/QMW_3_service.py
function/core/QMW_TipBattleSenior.py
function/core/QMW_TipEditorOfBattlePlan.py
function/core/QMW_TipLevel2.py
function/core/QMW_TipMisuLogistics.py
function/core/QMW_TipStageID.py
function/core/QMW_TipWarmGift.py

使用 3*双引号 跨行文本取代麻烦的累加.
使用 setFixedSize 直接固定相关UI大小. 懒得设定最大最小了.

style: 优化TipUI代码逻辑.

---

function/core_battle/CardManager.py

fix(cardmanager): 修复了高级战斗炸弹只能用一次的bug。

---

function/core/FAA.py
function/core_battle/Card.py
function/core_battle/CardManager.py
function/core_battle/CardQueue.py
function/core_battle/Coordinate_map.py
function/core_battle/FAA_Battle.py
function/core_battle/get_location_in_battle.py
function/globals/location_card_cell_in_battle.py
test/capture_card_state_image/main.py
test/test_大富翁.py

id和location代表from和to的代号.
coordinate_from和coordinate_to代表from和to位置的坐标.

style: 战斗方案处理. 位置和坐标相关变量进行统一. 

---

function/core/Todo.py

fix: 任务列表. 修复仅启动自定义任务序列时. 额外事项和自建房事项的日志输出和游戏刷新仍激活的Bug.

---

function/core/FAA.py
function/core/Todo.py

这个Bug是由于, 不同电脑上选中输入框时的特效是不一致的.
通过在校验前，添加一次点击取消输入状态，解决了这个问题.

fix: 日氪. 修复在部分电脑上无法正常完成流程的Bug.

---

config/settings_template.json
function/core/FAA_extra_readimage.py
function/core/QMW_2_load_settings.py
function/core/Todo.py
function/core_battle/CardManager.py
function/yolo/onnxdetect.py
resource/ui/FAA_3.0.ui

将 GPU 未启用时的警告日志级别从 warning 改为 debug，以便玩家可以正常看到此日志

style: 修改 GPU 未启用时的日志级别

---

function/core/QMW_EditorOfTaskSequence.py

这个Bug是由于初始化删除按钮时, 绑定了此时的i_id到删除函数上, 而非动态获取.
直接将删除按钮绑定到行元素解决了这个问题.
此外优化了一下此处的代码.

fix: 任务序列编辑器. 修复删除按钮绑定的上级元素错位问题.

---

function/core/Todo.py

这个Bug是由于傻卵AI一行的列表推导式都写不明白.
全项目最水PR, 改了一个字符!

fix: 自定义任务序列. 修复领取奖励执行问题.

---

README.md

- 更新 FAA 网络文档链接，增加内容说明
- 调整文档结构，精简重复信息
- 增加下载和关于部分的说明- 优化图片预览布局

docs(README): 更新文档首页信息

---

function/common/bg_img_match.py
function/core/FAA.py
function/core/QMW_3_service.py
resource/ui/FAA_3.0.ui

当超时时间为0时, 如果能一次尝试完成识图和后续操作, 现在将判定函数返回值为True.

refactor(目标识别): 重构识图点击功能. 极大降低部分高密度识图操作的等待时间.

---

function/core/QMW_2_load_settings.py
function/core/QMW_EditorOfBattlePlan.py
function/core/Todo.py
function/core_battle/Card.py
function/scattered/read_json_to_stage_info.py

* 罕见情况下, 复制类卡片未能直接通过读取已学习内容获得状态
* 复制类卡片实例缺乏放置函数 （手动置空了）
* 导致问题出现

fix(战斗执行器): 卡片状态图像自学习. 修复罕见情况下复制类卡片无限尝试学习但失败导致卡死的问题.

---

function/core/FAA_BattleARoundPreparation.py

具体拆解步骤:
1. 根据name字段获取每一张卡的 标识名 为 卡片精准名
2. 根据所有需要的卡片精准名 扫描一次, 找出所有可携带的卡片, 记忆位置
3. 根据每个标识名对应的可用精准名, 预匹配其唯一最佳 卡片精准名
4. 根据匹配结果和记忆位置快速完成查找.

refactor(自动带卡): 完全重构携带任务卡函数, 重构为自动带卡功能. 大幅优化逻辑, 极大加速运行速度.

---

function/core/FAA.py
function/core/FAA_BattlePreparation.py

* 预设图像可能出现的精确位置，避免大范围模板匹配, 性能极大提升
* 返回被禁止成功的卡槽编号, 以清理战斗方案，兼容性更佳

refactor(自动禁卡): 完全重构, 支持根据类型名称禁卡，性能提高1000倍+, 和自动带卡兼容性更佳

---

function/core/FAA.py

fix(公会任务): 修复限制卡片数量任务(坚果高台-夜) + 自动带卡 激活时会报错卡死的问题

---

config/settings_template.json
function/core/QMW_2_load_settings.py
function/core/QMW_3_service.py
function/core/Todo.py
function/core/Win_api.py
function/scattered/get_channel_name.py
resource/ui/FAA_3.0.ui

一键打开360大厅，一键杀死360大厅后台，以及弱保软按钮，按了它有神奇的力量（

feat(360游戏大厅开关): 新增自启动和关闭360游戏大厅功能. 新增弱保软按钮.

---

function/core/QMW_3_service.py
resource/ui/FAA_3.0.ui

原因:
* GAID的获取原理彻底解析后, 可知其获取难度更大.
* 通过更难获取的参数(GAID)来自动获取一个用户仅需拖动鼠标即可获取的参数(小号名称), 属实烂活!

perf(控制游戏大厅): 根据GAID, 获取360游戏大厅.exe路径和小号名称的功能中, 获取小号名称已移除. 此乃反向弱保软, 加大了用户的使用难度.

---

function/common/process_and_window_manager.py
function/core/QMW_3_service.py
function/core/QMW_EditorOfBattlePlan.py
function/core/QMW_EditorOfTaskSequence.py
function/core/Todo.py

* 目前复现率 1/50
* 复现成功案例: 使用定时任务间隔一分钟激活任务事项运行. 在事项todo结束退出后卡住. 具体需要更多细节.

style: 增加部分日志输出, 尝试排查偶发软件卡死的原因. 修正少量文本错误.

---

function/core/FAA.py
function/core_battle/Card.py

0s 放下幻鸡
1.5s 放下创造神
4.0s 幻鸡复制完毕
4.1s 创造神复制完毕，并被幻鸡顶开复制到周边位置.

perf(战斗执行器): 多复制卡优化, 采用先幻鸡后创造神的策略, 间隔1.5s, 最大限度缩短等待时间, 且不吞卡.

---

function/core/todo.py

大部分方案的2P为辅助, 一般不产火, 不放辅助, 甚至不放关卡对策卡...

fix(战前准备): 双线程单人作战时, P战斗方案现在将采用1P方案而非2P方案. 以确保其拥有完整的战斗力.

---

function/core/qmw_settings_migrator.py
function/scattered/check_battle_plan.py

原因：只写了v1 v2版本战斗方案的uuid的获取方式, 没写v3.

fix(配置迁移工具): 修复无法迁移 版本为v3的战斗方案 的问题.

---

function/core/faa/faa_core.py

因为遭遇网络问题后, 将跳转到其他的网页, 只是刷新游戏重试没用, 必须返回上一级网页才能稳定解决问题.

fix(刷新游戏): 刷新游戏若遭遇网络问题, 在原有的先点击红色重试按钮后, 新增操作返回上一级. 确保复位.
