function/battle/CardManager.py
function/core/FAABattle.py
function/core/Todo.py

为战利品日志记录中, 每个关卡的记录下, 添加了本场战斗是否使用钥匙的键, 以对此进行区分. 为实现该功能, 拆分了检测钥匙使用和检测战斗结束的函数, 并添加了对应的信号以完成跨窗口(FAA不同实例)的传参.

v1.3.1 战利品日志记录中, 每个关卡的记录下,将区分本场战斗是否使用钥匙. 

---

function/core/FAA.py
function/core/QMW_1_load_settings.py
function/core/QMW_3_service.py
function/core/Todo.py
function/scattered/TodoTimerManager.py

重新整理了多方案情况下, 定时启动和编辑方案的逻辑.
已完成了正在编辑的方案和正在运行的方案的分离: 开始运行后, 将以启动时的方案的拷贝为准, 以进行各项自动化流程的进行, 编辑不会影响正在运行中的流程, 需要重新开始以进行应用. 增加了正在运行的方案和正在编辑的方案的ui文本/运行输出/提示信息, 以向用户反映这种变化.

v1.3.1 重新整理多方案下, 定时启动和编辑方案的逻辑. 启动后将锁定配置, 不应用实时更新.

---

function/core/Todo.py

v1.3.1 修复了在多线程单人模式时, 其中一个号卡死会导致正常运行的另一号同时reload, 导致报错卡死的bug. 

---

function/core/FAA_Battle.py
function/core_battle/Card.py

动作队列在部分cpu较差的机型上, 生产者速度>消费者速度问题, 经过约两周的排查(摸鱼), 已大体解决问题.
问题来自Card生产者中, 由于统计结算每次放卡的sleep而非每次添加点击后单独sleep, 且faa采用一进程多线程架构, 导致消费者线程无法得到时间片, 将对应的sleep改为每次添加动作后激活, 彻底解决了该问题.

v1.3.1 动作队列在部分cpu较差的机型上, 生产者速度>消费者速度问题, 尝试解决.

---

function/core_battle/CardManager.py

更新动作队列日志, 在每次战斗前和战斗后 输出距离上一次进行该操作期间, 进行了多少次鼠标队列生产和消费, 以判断是否出现严重的队列积压.

v1.3.1 动作队列日志, 在每次战斗前和战斗后 输出距离上一次进行该操作期间, 鼠标队列的进出次数.

---

function/core_battle/Card.py

更新战斗中单张卡放置时的流程中的时延, 以确保截图能在对应的动作完成后进行, 提高稳定性, 尽可能降低识别失败导致一致尝试使用某张已经放满的卡的情况的出现.

v1.3.1 自动战斗. 放卡后 检测状态前 的延时增加, 以提高识别到卡片放满的成功率. 防止一直尝试放置放满的卡片.

---

function/core/FAA.py

因为承载和任务卡优先级超过了产火卡. 
这会导致风化+0能耗承载的玩家晚7s开始放置承载卡 orz,
但考虑到对于地产玩家问题更严重, 故进行该修改.

v1.4.0-beta.4 自动战斗 - 自动承载/任务卡. 其插入位置不再是首位, 而是第二位, 解决部分无风化玩家的开局产火问题. 

---

function/core/FAA.py
function/core/FAA_Battle.py
function/core/Todo.py
function/core_battle/CardManager.py

一个古老的问题, 遗漏了是否使用钥匙参数, 导致无论如何设置, 都会使用钥匙. 
修复了该问题, 仅在需要使用钥匙时判断识图点击钥匙, 且当钥匙被使用后, 本场作战中不再尝试识图钥匙节省开销.

v1.4.0-beta.4 战斗执行器 - 使用钥匙. 完成了该被遗漏的功能.

---

function/core/FAA_BattleARoundPreparation.py

将原本的 7轮 x 3次 拖动窗口下拉条, 改为 11轮 x 2次. 
以解决部分背包格子较多的用户无法正常选择任务卡的问题. 
注: 该游戏每次点击下拉条按钮, 是固定向下拖动整体的1/20

v1.4.0-beta.9 自动战斗 - 战前准备 - 选任务卡. 解决部分背包格子较多的用户无法正常选择任务卡的问题. 

---

function/core/Todo.py

主要流程.
修复了双人魔塔和萌宠神殿交换顺序后, 萌宠神殿完成后不进行退出动作, 导致需触发刷新游戏防卡死才能进行接下来的双人魔塔. 
是由于原本萌宠神殿之后总会刷新游戏, 故未填写结束后动作, 现已修正该问题.

v1.4.0-beta.10 修复双人魔塔和萌宠神殿交换顺序后, 萌宠神殿完成后不退出, 需触发防卡死才能正常继续的问题.

---

function/core_battle/Card.py

v1.5.0-beta.1 兼容自动炸弹时, 无location_to的卡片不被移除, 导致战斗线程崩溃的bug完成修复

---

function/core/analyzer_of_loot_logs.py
function/scattered/match_ocr_text/match_text.py

文字识别&战利品识别.
识别失败, 保留图片时, 应用最小未使用id, 而不再使用非文件数做id, 以处理撞文件名导致的闪退问题.

v1.5.0-beta.2 文字识别&战利品识别. 识别失败, 保留图片时, 应用最小未使用id, 而不再使用非文件数做id, 以处理撞文件名导致的闪退问题.

---

function/core_battle/Card.py

fix(战斗执行器-状态识别): 修复点击队列混乱的问题

---

function/core/QMW_2_load_settings.py

该问题是由于FAA是通过选中的index找到按名称排序的战斗方案名称. 再根据名称找到对应的uuid并保存的. 因此如果不是退出faa再修改战斗方案名称, 会导致该问题出现. 改用setData到每个下拉框的item中以记录uuid和选项的映射, 彻底解决了该问题.

fix: ui和opt数据交互. 修复改名方案, 不退出faa而直接点击保存, 会导致当前选中的Todo方案的战斗方案错位的问题.

---

function/scattered/match_ocr_text/match_text.py

该问题是由于防止重复图像保存功能扫描错了文件夹. 导致重复的图像不断堆积, 导致识别负担越来越大.

fix: OCR. 修复识别失败图像保存时, 越来越卡顿的问题.

---

function/scattered/loots_and_chest_data_save_and_post.py

一个极其低级的失误.
导致连通性测试可以通过, 上传总是失败.

fix: 修复米苏物流使用默认url时上传失败的问题.

---

function/core/FAA.py

perf: 日氪. 修复 充值界面-复核-已选中氪金值输入框 步骤 错误的问题.

---

function/core/FAA.py

- 在 FAA.py 文件中，为匹配到的卡片信息增加了 'coordinate_from' 字段
- 这个字段记录了卡片的原始坐标，便于后续处理和追踪
- 虽然这个炸前放垫子实现了，但是实测下来最好还是自行将垫子信息写到战斗方案中，不然用起来比较难蚌

fix: 为匹配到的卡片添加坐标信息,修复炸弹前放置垫子会因为索引不存在导致线程爆炸问题

---

function/scattered/guild_manager.py

fix: 删去工会管理器的翻页20次限制

---

function/core/FAA.py
function/core/FAA_BattlePreparation.py
function/core/Todo.py

原本进入房间失败时, 带卡也跟随失败.
带卡失败 导致更高级的第三级防卡顿函数(跳过本关所有战斗)优先激发.
覆盖了由进入房间失败激发的第二级防卡顿函数(跳过本关本次战斗),

fix: 拆分[战前准备工作]为[确定进入房间]和[带卡]两步. 使用自动带卡且进入房间失败时, 会直接跳过本关所有次数的问题已修复.

---

config/settings_template.json
function/core/FAA_BattlePreparation.py
function/core/Todo.py
function/core/analyzer_of_loot_logs.py

游戏内的掉落物实际视图排序:
高优先级物品 -> 绑定四叶草 -> 不绑定四叶草 -> 技能书 -> 绑定香料 -> 不绑香料 -> 低优先级物品
此前，错误的认为 同种四叶草和香料的视图, 绑定和不绑会连续.
这导致  有向无环图校验和物品连续性 在部分合法情况下仍无法通过.
例： 绑定3级四叶草 -> 绑定1级四叶草 -> 不绑定2级四叶草 -> 不绑1级四叶草. 合法但无法通过两种校验.
解决方案:
- 物品连续性校验: 提供白名单, 相关物品不校验连续性.
- 有向无环图校验: 为对应物品提供分组手动排序至预定顺序.

fix(战利品识别): 修复有向无环图校验和物品连续性校验的一项重大Bug. 游戏内掉落物(四叶草/香料)若在单局中以特定顺序同时出现绑定和非绑定, 不再会导致校验失败判定为无效数据.

---

function/core/FAA.py
function/core/FAA_extra_readimage.py
function/core/QMW_1_log.py
function/core/Todo.py
function/core/performance_analysis.py
resource/ui/FAA_3.0.ui

核心矛盾: try times 的定义发生更改后代码没有做相应更新. (总计次数 -> 单角色次数)
* 老版游戏无法对同一公会多次施肥，因此需要大量尝试，并让2P继承1P的进度继续，防止重新对近百个公会做无效尝试
* 新版则不再需要，仅需尝试1+3个公会即可顺利完成任务. 第一个公会可能存在没有种树的问题.
* 后果1
* 1P计数继承到2P后，如果1P正好是5次完成任务，继承次数的2P可能直接绕过计数==5的中断机制，导致无限施肥产生。
* 后果2
* 1P完成三次任务后，计数为3
* 2P完成两次任务后，计数为2，触发5次一reload的防卡死.
* reload后完成任务.

fix(浇水 施肥 摘果): 为跟进可重复施肥的游戏改动进行的修正不完全, 导致两个角色间继承尝试次数计数, 进而在罕见情况下产生无限施肥. 对该问题进行了修正.

---

function/core_battle/CardManager.py

该问题触发条件较为苛刻. 需要以下条件.
1. 关卡的最终boss死亡后, 波次产生变动. (多拿滋星云)
2. 用户为该波次设置了变阵. 进而几乎同时触发重载变阵和结束战斗信号.
具体来说, 先触发子线程stop两次, reinit一次(部分参数已为None), 直接进行了子线程的run(), 此时部分线程因错误捕获, 而持续进行操作.
修改方案:
1. 捕获一次错误后, 立刻中止循环检测线程, 防僵尸线程.
2. 添加running属性于战斗管理器类, 以规避子线程的批量启动和中止被重复调用.

fix(战斗执行器内核): 修正一个罕见的问题, 该问题导致僵尸检测线程出现, 虽不影响流程, 但会输出大量warning日志.

---

function/core/faa/faa_battle_preparation.py
function/core/faa/faa_core.py
function/core/todo.py
function/globals/EXTRA.py
function/scattered/loots_and_chest_data_save_and_post.py
function/scattered/match_ocr_text/text_to_battle_info.py
function/scattered/read_json_to_stage_info.py
resource/ui/FAA_3.0.ui

* 该问题的来源
* 此前一项补丁, 允许用户在自建房处自由输入stageid.
* 并以该id获取关卡信息, 全局关卡方案等参数, 以支持更方便的自建房.
* 此前FAA未能区分业务逻辑的id(除自建房外, 还包括魔塔自动爬塔即层数为0时的情况)与实际地图的id.
* 后果
* 这导致少量未知关卡名称的脏数据流入了米苏物流.
* 关卡A中流入了部分关卡B的数据.(因为用户可以自由输入关卡id)
* 解决方案
* 明确划分两种关卡id的来源和用途.
* 业务id为所有地图id加上 CU-0-0, MT-1-0, MT-2-0, PT-0-0. 用于米苏物流的输出和内部的模式判别. 
* 关卡id, 默认继承自业务id, 如果为自建房, 则修改为用户的输入, 之后再由关卡名称OCR进行二次更正. 用于获取关卡的信息和全局方案.
* 增加更多调试信息以纠错.
* 加入白名单机制. 要求用户必须输入白名单内的关卡id. 否则对应操作直接跳过.

fix(战斗流程): 修复一项重大bug. 区分战斗的模式id和实际地图id. 以修复用户在自建房随意输入关卡id后, 错误的id为参数生成的战斗结果, 被上传至米苏物流, 造成数据污染的问题. 并增加了更精细的调试信息, 以测试该问题.

---

function/core/todo.py

为了在可双人的关卡单人作战时, 若在全局&关卡方案设置了仅作为辅助的不完整的2P方案, 如果1P和2P使用各自的方案, 2P将无法完成单人作战. 修改后, 将根据该关卡本身是否为仅单人, 进行判定.
双人关卡双人：使用各自方案.
双人关卡单人：都用1P方案.
单人关卡单人：都用1P方案(旧) -> 使用各自方案(新)

perf(全局&关卡方案): 对于仅单人关卡, 2P不再使用1P方案, 对于可双人关卡的单人作战则不变.
